### PR TITLE
cmd/tsdbrelay: enable version numbers, fix metadata, add error metrics

### LINKED ISSUE #1792: tsdbrelay doesn't support -version flag
We will now be including tsdbrelay in the docker container so it supports ledis backed counters. The tsdbrelay binary does not currently support the -version flag, which it should so we can see what commit it was built from.

Once this is working we will need to update https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/docker/build/Dockerfile#L35 to include a call to tsdbrelay -version

### PR DESCRIPTION
**Pull request by gbrayut**
Also:
removes runtime.GOMAXPROCS(runtime.NumCPU()) since that is now the default
tabs to spaces in docker.sh
updates docker image to use to go1.7.linux-amd64.tar.gz
fixes missing call to metadata.init
adds metrics for tracking errors from opentsdb/bosun
adds metrics for tracking relayed/errors from secondary relays.

~~This also changes the logic so that data points are always relayed to bosun and secondary relays instead of bailing when the primary opentsdb end point returns an error.~~ Will keep thinking on this and open a separate PR.

Fixes #1792

### CODE REVIEW

File: cmd/tsdbrelay/main.go [hunk 1]
```diff
@@ -14,6 +15,8 @@ import (
 	"os"
 	"strings"
 
+	version "bosun.org/_version"
```
Comment (gbrayut) [inline cmd/tsdbrelay/main.go]: @captncraig I'm curious why I had to put an alias here. Locally using go 1.6.3 it can't find the reference to version package and gives an error/removes the import if I try to use a default import or even the _ import. Scollector/Bosun seem to work fine without the alias.

Comment (captncraig) [inline cmd/tsdbrelay/main.go]: I can't explain why. If it helps to remove the alias, go ahead, but it sounds like something odd may be going on with your go environment.

**Comment by gbrayut** [comment]
I'm going to test this on ny-gbraylx01, which uses tsdbrelay to forward to a local docker instance and an influxdb instance and relay to the primary bosun instance.

@captncraig please review when you have time

**Comment by gbrayut** [comment]
Hmm... Metadata is working now but it still doesn't always relay. I'll keep working on this.

**Comment by gbrayut** [comment]
This approach isn't going to work. The reverse proxy generates a 500 response code if there is a connection issue to the primary target and immediately sends that to the client. So even if we still try forwarding the data points to the other endpoints the scollector client will have those same data points queued up to be retried, resulting in duplicate data.

I think there is a simpler way to solve the issue of HA forwarding, so I'm going to bundle up the other commits and push those to master, since they fix a bunch of non forwarding related issues.

**Comment by gbrayut** [comment]
This branch now has all the non-forwarding related changes. I plan on merging it tomorrow (testing on ny-gbraylx01 overnight)
