### PR TITLE
cmd/bosun: Add an API route to return all metrics and their associate…

### LINKED ISSUE #1245: Bosun: /api/tagk to get all current tags across all metrics (also support basic filtering)
We were trying to find if a current tag is used, but the API doesn't have a route to return all tags. We could use the /api/metric route to get all metrics and then call /api/tagk/{metric} but it would be better if there was a /api/tagk route that returned a list of all metrics and tags.

/api/metadata/get has the information, but also includes other metadata which makes it an expensive call. The /api/tagk route could use the same format but just exclude the extra data:

[{"Metric":"os.disk.fs.space_used","Tags":{"disk":"/opt/gitlab"}},{"Metric":"web.comment.edited","Tags":{"host":"ny-web04","role":"coreqa","site":"datascience.stackexchange.com"}},{"Metric":"elastic.indices.suggest.current","Tags":{"cluster":"StackExchangeNetwork","index_name":"careers-full-cv-candidate-search-635643440065754201"}}]

The /api/metadata/get route is also close to what we would need when you provide a query string, but ?tagk=tagname doesn't work by itself (error: "unpaired tagk/tagv") or allow globs. The ability to request /api/tagk?tagk=tagname to find all metrics using a specific tag would be very helpful.

### PR DESCRIPTION
**Pull request by kylebrandt**
…d keys

Fixes #1245

### CODE REVIEW

File: cmd/bosun/search/search.go [hunk 1]
```diff
@@ -284,6 +284,20 @@ func (s *Search) TagKeysByMetric(Metric string) []string {
 	return r
 }
 
+func (s *Search) TagKeysByMetricTree() map[string][]string {
```
Comment (captncraig) [inline cmd/bosun/search/search.go]: This name does not describe to me what it actually does. Which is the top level key? I am assuming the hierarchy is `metric -> all tagks`. Perhaps `MetricsWithTagKeys` would make a bit more sense.

File: cmd/bosun/search/search.go [hunk 2]
```diff
@@ -284,6 +284,20 @@ func (s *Search) TagKeysByMetric(Metric string) []string {
...
+	metricToKeys := make(map[string][]string)
+	searchResult := s.Read.Tagk.Copy()
+	for metric, v := range searchResult {
+		metricToKeys[metric] = make([]string, len(v))
+		i := 0
+		for tK := range v {
+			metricToKeys[metric][i] = tK
```
Comment (captncraig) [inline cmd/bosun/search/search.go]: For readability I recommend making and filling the slice, and then putting it into `metricsToKeys` at the end of the loop. That may reduce the chained map/slice indexing.

File: cmd/bosun/web/web.go [hunk 3]
```diff
@@ -99,6 +99,7 @@ func Listen(listenAddr string, devMode bool, tsdbHost string) error {
 	router.Handle("/api/metadata/put", JSON(PutMetadata))
 	router.Handle("/api/metric", JSON(UniqueMetrics))
 	router.Handle("/api/metric/{tagk}/{tagv}", JSON(MetricsByTagPair))
+	router.Handle("/api/metric/keytree", JSON(TagKeysByMetricTree))
```
Comment (captncraig) [inline cmd/bosun/web/web.go]: Naming here is harder yet. `keytree` is not super descriptive to me. You can call it what you want though.
